[cda_paths]
csv_path = "../resources/data.csv"
excel_path = "../resources/CDAVariables.xlsx"
xslt_file = "../resources/EmergencyNote.xslt"
output_dir = "../output/"

[csv_paths]
cities_csv = "../resources/value_sets/clinics.csv"
diagnoses_csv = "../resources/value_sets/icd10gm2023.csv"
cedis_csv = "../resources/value_sets/cedis.csv"